### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ruitjes** [psychogen-labs/spring-rest-over-ws#4]
Sorry not really an issue, more a quick question.

Can I use this library to achieve my goal here: https://stackoverflow.com/questions/65107713/spring-boot-rest-api-with-websockets

**Comment by sepgh** [comment]
Hi @Ruitjes , I took a look at your project. It seems possible to use ROW in your project, but I haven't written any JavaScript client yet. Maybe you would want to look at **Stomp** protocol since it has JS support as well. So, be noticed that If you use ROW, you almost wont need to configure anything on spring side and your controller is just fine, but you will need to follow [protocol message structures](https://github.com/idioglossia/spring-rest-over-ws/wiki/Protocol) on client side.

**Comment by Ruitjes** [comment]
I heard a lot of things about Stomp, but i'm not sure how to get websockets working with my Rest API.

**Comment by sepgh** [comment]
Unlike ROW stomp doesn't wrap your Rest API, but there are similar annotations and ideas for stomp. I'm sure you will be able to find lots of examples online. But in the end you have to make a little change to your current codes and controller.
